name: Road Closure ETL Update - Report Project

on:
  schedule:
    - cron: '30 5 * * *'  # 12:30am EST/EDT (America/New_York is UTC-5/UTC-4)
  workflow_dispatch:

permissions:
  contents: write

jobs:
  run-etl-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Run ETL script
        run: node etl_data.js

      - name: Configure git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Add all changed files
        run: git add .

      - name: Commit changes
        run: git diff --cached --quiet || git commit -m "Automated nightly ETL update [skip ci]"

      - name: Pull latest changes
        run: git pull --rebase

      - name: Push changes to repository
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: git push
